Repository Priyadarshan2000/Hacktoberfest_2k22, pull requests merged in 2022-10, with the labels that each got.

#1 code to check if two strings are anagram or not
  Kadane's Algo.c
  Strings-anagram.c
Labels: Hacktoberfest Accepted

#2 Create Circular Queue
  Circular Queue
Labels: Hacktoberfest Accepted

#3 Create DSA folder and .cpp file
  DSA/Valid Palindrome Strings.cpp
Labels: Hacktoberfest Accepted

#4 Created a new file.
  contact-management-system.c
Labels: Hacktoberfest Accepted

#6 Tree Implementation
  treerepresentation.cpp
Labels: Hacktoberfest Accepted

#8 Rename Circular Queue to Circular Queue.java
  Circular Queue.java
Labels: Hacktoberfest Accepted

#9 Create Maximum Sub Array
  DSA/Maximum Subarray
Labels: Hacktoberfest Accepted

#10 Create Contains Duplicate
  DSA/Contains Duplicate
Labels: Hacktoberfest Accepted

#11 Create Plus One
  DSA/Plus One
Labels: Hacktoberfest Accepted

#12 Create Array from Permutation
  Build Array from Permutation
Labels: Hacktoberfest Accepted

#13 codes of Hash table and circular queue.
  DSA/Hash Table.java
  DSA/circular queue
Labels: Hacktoberfest Accepted

#14 check
  DSA/Harshad number .c
  DSA/Minimum scalar product.c
  DSA/besttimebuysellstock.c
Labels: Hacktoberfest Accepted

#18 Add files via upload
  reverseanaraay.cpp
  subarray2.cpp
Labels: Hacktoberfest Accepted

#20 Add files via upload
  duplicateeleinarr.cpp
  string_palindrome.cpp
  vector trial.cpp
Labels: Hacktoberfest Accepted

#21 Add files via upload
  fab.cpp
  trr.cpp
Labels: Hacktoberfest Accepted

#19 Largest Sum Contigous SubArray
  DSA/largestsumofcontiguoussubarray.c
Labels: Hacktoberfest Accepted

#17 remove brackets from an algebraic expression
  DSA/removebrackets.c
Labels: Hacktoberfest Accepted

#16 Create delete from end in doubly linked list.cpp
  DSA/Minimum edges to reverse to make path from a source to a destination.cpp
  DSA/delete from end in doubly linked list.cpp
Labels: Hacktoberfest Accepted

#22 NOTE_TAKING_APP
  Note_taking_app/Other.js
  Note_taking_app/app.js
  Note_taking_app/custom.css
  Note_taking_app/dp.png
  Note_taking_app/index.html
Labels: Hacktoberfest Accepted

#24 Create Anagram.cpp
  DSA/Anagram.cpp
  DSA/check_palindrome.cpp
  check_palindrome.cpp
Labels: Hacktoberfest Accepted

#25 Create search_insert.cpp
  DSA/Merge_sort.c
  DSA/floyd.c
  DSA/search_insert.cpp
  OOPS/inheritence.java
Labels: Hacktoberfest Accepted

#31 Added all files of hoverboard project
  Hoverboard/hoverboard.html
  Hoverboard/script.js
  Hoverboard/style.css
Labels: Hacktoberfest Accepted

#23 Remove Special Character from String
  Remove Special Character from String.java
Labels: Hacktoberfest Accepted

#32 added a code of constructor overloading and this() concept
  OOPS/ConstructorOverloading.java
Labels: Hacktoberfest Accepted

#26 Add files via upload
  OOPS/DynamicMethodDispaching.java
Labels: Hacktoberfest Accepted

#28 Added A.2_3 moves.cpp
  A.2_3 moves.cpp
Labels: Hacktoberfest Accepted

#30 Constructor
  OOPS/Constructor.cpp
Labels: Hacktoberfest Accepted

#33 Minimum Path Sum
  DSA/Minimum_path_sum.txt
Labels: Hacktoberfest Accepted

#34 Create Height_of_a_Binary_Tree.cpp
  DSA/Height_of_a_Binary_Tree.cpp
Labels: Hacktoberfest Accepted

#35 1578. Minimum time to make rope colorful using DP
  DSA/LeetCode/1578-minimum-time-to-make-rope-colorful/1578-minimum-time-to-make-rope-colorful.cpp
  DSA/LeetCode/1578-minimum-time-to-make-rope-colorful/NOTES.md
  DSA/LeetCode/1578-minimum-time-to-make-rope-colorful/README.md
Labels: Hacktoberfest Accepted

#37 Job Sequencing
  job_sequencing.c
Labels: Hacktoberfest Accepted

#40 Kadanes_algo and Josephus_problem
  DSA/Josephus_problem.c
  DSA/Kadanes_algo.c
Labels: Hacktoberfest Accepted

#39 added binary search code
  binarysearch.cpp
  reversearray.cpp
Labels: Hacktoberfest Accepted

#42 Create Palindrome.cpp
  DSA/Palindrome.cpp
Labels: Hacktoberfest Accepted

#45 Create Sunny Number.java
  Sunny Number.java
Labels: Hacktoberfest Accepted

#52 Create Distance.java
  DSA/Distance.java
Labels: Hacktoberfest Accepted

#53 Create Nknight.java
  DSA/Nknight.java
Labels: Hacktoberfest Accepted

#55 Create MaxWidth.java
  DSA/MaxWidth.java
Labels: Hacktoberfest Accepted

#56 hacktoberfest-2022
  egg_dropping_puzzle.cpp
Labels: Hacktoberfest Accepted

#57 NewDistance.java
  DSA/JobSequence.java
  DSA/NewDistance.java
Labels: Hacktoberfest Accepted

#58 Create NewJobSequence.java
  DSA/NewJobSequence.java
Labels: Hacktoberfest Accepted

#59 Create Login and registration system using C++
  Login and registration system using C++
Labels: Hacktoberfest Accepted

#46 added leetcode max sum in array in c++
  leetcode-maxSum
Labels: Hacktoberfest Accepted

#49 Create Counting sort.cpp
  Counting sort.cpp
Labels: Hacktoberfest Accepted

#60 Add files via upload
  DSA/Sudoku.java
Labels: Hacktoberfest Accepted

#62 Add files via upload
  DSA/QueueUsingStack.java
Labels: Hacktoberfest Accepted

#63 Add files via upload
  DSA/KosaRaju.java
Labels: Hacktoberfest Accepted

#64 Add files via upload
  DSA/MaxWidth.java
Labels: Hacktoberfest Accepted

#50 Guess the Number
  Guess the Number/Guess_number.py
  Guess the Number/README.md
  Guess the Number/best_score.txt
Labels: Hacktoberfest Accepted

#51 hacktoberfest-2022
  linked_list.c
Labels: Hacktoberfest Accepted

#54 Add files via upload
  DSA/BinarySearch.java
Labels: Hacktoberfest Accepted

#61 Create googleKickstart_Hex.py
  googleKickstart_Hex.py
Labels: Hacktoberfest Accepted

#66 Create First and Last element of an array
  First and Last element of an array
Labels: Hacktoberfest Accepted

#67 Sieve_of_Eratosthenes
  DSA/Sieve_of_Eratosthenes.c
Labels: Hacktoberfest Accepted

#68 Create DFS_Traversal.cpp
  DSA/DFS_Traversal.cpp
Labels: Hacktoberfest Accepted

#69 Add files via upload
  DSA/Floyd.c
Labels: Hacktoberfest Accepted

#70 Soduku solver is added
  Soduku_solver.cpp
Labels: Hacktoberfest Accepted

#71 Implement queue using two stacks
  DSA/implement_queue_using_stacks.cpp
Labels: Hacktoberfest Accepted

#74 Conversion of Celsius to Fahrenheit & Fahrenheit to Celsius
  OOPS/Celsius_Fahrenheit.cpp
Labels: Hacktoberfest Accepted

#75 Create Max_Consecutive_Ones.cpp
  DSA/Max_Consecutive_Ones.cpp
Labels: Hacktoberfest Accepted

#79 Leetcode Solution --> Maximum Subarray
  Leetcode-53_Maximum-Subarray/Approach-to-Solution.txt.txt
  Leetcode-53_Maximum-Subarray/Problem Statement.txt
  Leetcode-53_Maximum-Subarray/Solution.cpp
Labels: Hacktoberfest Accepted

#77 added merge-sorted-array
  DSA/merge-sorted-array
Labels: Under review

#76 added Insertion_of_node_at_tail_of_LinkedList
  DSA/Insertion_of_node_at_tail_of_LinkedList.cpp
Labels: Hacktoberfest Accepted

#80 program for diagonal traversal of binary tree
  DSA/diagonalTraversalOfBinaryTree.cpp
Labels: Hacktoberfest Accepted

#83 Hacktoberfest-2022
  DSA/post_order_traversal.cpp
Labels: Hacktoberfest Accepted

#84 Hacktoberfest-2022
  DSA/pre_order_traversal.cpp
Labels: Hacktoberfest Accepted

#85 Hacktoberfest-2022
  OOPS/polymorphism.java
Labels: Hacktoberfest Accepted

#86 Update index.html
  Note_taking_app/index.html
Labels: Hacktoberfest Accepted

#87 Rename app.js to ap.js
  Note_taking_app/ap.js
Labels: Hacktoberfest Accepted

#82 graph-coloring-using-backtracking-algorithm.cpp
  graph-coloring-using-backtracking-algorithm.cpp
Labels: Hacktoberfest Accepted

#95 Add files via upload
  count substring in a string.cpp
Labels: Hacktoberfest Accepted

#81 Dice Game
  Dice Game/dicee.html
  Dice Game/images/dice1.png
  Dice Game/images/dice2.png
  Dice Game/images/dice3.png
  Dice Game/images/dice4.png
  Dice Game/images/dice5.png
  Dice Game/images/dice6.png
  Dice Game/index.js
  Dice Game/styles.css
Labels: Hacktoberfest Accepted

#88 Add files via upload
  CRC/CRCReciever.java
  CRC/CRCsender.java
  Hamming Code/HammingReciever.java
  Hamming Code/HammingSender.java
Labels: Hacktoberfest Accepted

#90 Area_Triangle_Rectangle_Square
  OOPS/Area_Triangle_Rectangle_Square.cpp
Labels: Hacktoberfest Accepted

#92 Add files via upload
  DSA/Sort_array_of_0s_1s_2s.cpp
Labels: Hacktoberfest Accepted

#93 I have added Word Scramble Game using html,css and js
  Word Scramble Game using html css and js/Word_Scramble.html
  Word Scramble Game using html css and js/bg.mp3
  Word Scramble Game using html css and js/correct.mp3
  Word Scramble Game using html css and js/list.js
  Word Scramble Game using html css and js/over.mp3
  Word Scramble Game using html css and js/script.js
  Word Scramble Game using html css and js/style.css
  Word Scramble Game using html css and js/wrong.mp3
Labels: Hacktoberfest Accepted

#97 knapsack algorithm
  knapsack_problem.cpp
Labels: Hacktoberfest Accepted

#105 Median of two sorted arrays of equal size in C
  DSA/Abundant-Number.c
  DSA/Medianof2sortedarray.c
  DSA/Sandwich-Inverted-pattern.c
  DSA/Specificpairmatrix.c
Labels: Hacktoberfest Accepted

#94 Construtor Implementation
  classconstrutor.cpp
Labels: Hacktoberfest Accepted

#96 Text_to_speech.py
  Text_to_speech.py
Labels: Hacktoberfest Accepted

#100 Subarrays with equal 1s and 0s
  DSA/Subarrays with equal 1s and 0s.cpp
Labels: Hacktoberfest Accepted

#104 Create BitManipulation.cpp
  DSA/BitManipulation.cpp
Labels: Hacktoberfest Accepted

#102 Rock-Paper-Scissors
  Rock Paper Scissors/README.md
  Rock Paper Scissors/Rock_Paper_Scissors.py
Labels: Hacktoberfest Accepted

#101 two C++ codes
  possible_words_frm_phn_digits.cpp
  spirally_traverse_matrix.cpp
Labels: Hacktoberfest Accepted

#111 Create Transpose of matrix.C
  Transpose of matrix.C
Labels: Hacktoberfest Accepted

#103 Create largest_element_in_the_array.cpp
  DSA/largest_element_in_the_array.cpp
Labels: Hacktoberfest Accepted

#106 Stone Paper Scissor
  StonePaperScissor.java
Labels: Hacktoberfest Accepted

#107 Created catalan_number.cpp
  catalan_number.cpp
Labels: Hacktoberfest Accepted

#117 nCr
  EuclidsAlgoGCD.cpp
  FunctionnCr.cpp
  R4_fibonacci.cpp
Labels: Hacktoberfest Accepted

#108 Create length of loop cycle in given Linked List.cpp
  DSA/length of loop/cycle in given Linked List.cpp
Labels: Hacktoberfest Accepted

#109 House Design
  House_Design/Luxurious-interior-design-living-room-and-fireplace-in-a-beautiful-house-scaled.jpeg
  House_Design/index.html
  House_Design/logo_1.jpg
  House_Design/style.css
Labels: Hacktoberfest Accepted

#131 encapsulation in java
  OOPS/Encapsulation.java
Labels: Hacktoberfest Accepted

#125 added code for abstraction in java
  OOPS/Abstraction.java
Labels: Hacktoberfest Accepted

#130 Return the matrix in reverse spiral form.
  DSA/Reverse Spiral Form of Matrix.cpp
Labels: Hacktoberfest Accepted

#129 tic tac toe
  game.py
Labels: Hacktoberfest Accepted

#120 Sandwich Inverted pattern
  DSA/Sandwich Inverted.c
Labels: Hacktoberfest Accepted

#121 median in a row wise sorted matrix
  DSA/Medianrowsortmatrix.c
Labels: Hacktoberfest Accepted

#122 specific pair in matrix
  DSA/specificpairmat.c
Labels: Hacktoberfest Accepted

#112 Addition, Subtraction, Multiplication, Division of two complex numbers.
  OOPS/ComplexNo_Add_Sub_Mul_Div.cpp
Labels: Under review

#118 Queue_using_linkedlist.cpp
  DSA/Queue_using_linkedlist.cpp
Labels: Hacktoberfest Accepted

#133 Abstract class
  OOPS/AbstractClass.java
Labels: Hacktoberfest Accepted

#119 Loading by animation
  loadinganimation.html
  style.css
Labels: Hacktoberfest Accepted

#142 Create Neon.cpp
  DSA/Neon.cpp
Labels: Hacktoberfest Accepted

#134 Created TOMJERRY game
  Tom&JerryGame/README.md
  Tom&JerryGame/bg.png
  Tom&JerryGame/gameover.mp3
  Tom&JerryGame/jerry.png
  Tom&JerryGame/logo.png
  Tom&JerryGame/music.mp3
  Tom&JerryGame/script.js
  Tom&JerryGame/style.css
  Tom&JerryGame/tom.gif
  Tom&JerryGame/tomjerry.html
Labels: Hacktoberfest Accepted

#143 Create Note_app
  DSA/Bellmanford.c
  Note_app/app.js
  Note_app/note_app.html
Labels: Hacktoberfest Accepted

#145 Add files via upload
  DSA/sort according the number of ones in binary from.cpp
Labels: Hacktoberfest Accepted

#126 Craete bubble sort in C++
  bubbleSort.cpp
Labels: Hacktoberfest Accepted

#127 Added a program to check Special Number
  SpecialNumber.java
Labels: Hacktoberfest Accepted

#135 longest common subsequence
  longest_common_subsequence.cpp
  subset_sum_equal_to_target.cpp
  subset_sum_equal_to_target.exe
Labels: Hacktoberfest Accepted

#136 Pull5
  longest_common_subsequence.cpp
  subset_sum_equal_to_target.cpp
  subset_sum_equal_to_target.exe
Labels: Under review

#128 added Array Of Object
  OOPS/ArrayOfObject.java
Labels: Hacktoberfest Accepted

#132 Added code of Letter combination of Phone keyword
  phone_keyword.cpp
Labels: Hacktoberfest Accepted

#137 Create cscan.py
  cscan.py
Labels: Hacktoberfest Accepted

#138 Add files via upload
  MyUDPClient.java
  MyUDPServer.java
Labels: Hacktoberfest Accepted

#139 Add files via upload
  journeyOfTheKnight.cpp
Labels: Hacktoberfest Accepted

#140 Add files via upload
  SortingComparetor.java
Labels: Hacktoberfest Accepted

#144 Added Segment Tree implementation in C++
  SegmentTree.cpp
Labels: Hacktoberfest Accepted

#146 floyd warshall algorithm cpp
  DSA/floyd warshall.cpp
Labels: Hacktoberfest Accepted

#147 Create IntersectionOfTwoArrays
  IntersectionOfTwoArrays
Labels: Hacktoberfest Accepted

#149 windows shutdown using c language.
  windows shutdown using c/windowsShutDown.c
Labels: Hacktoberfest Accepted

#155 added dijkstra algorithm in cpp
  DSA/Dijkstra_algorithm.cpp
Labels: Hacktoberfest Accepted

#150 Create palindrome.cpp
  DSA/palindrome.cpp
  DSA/swap_Nodes_in_pairs.cpp
Labels: Hacktoberfest Accepted

#157 Create Longest_Valid_Parentheses.cpp
  DSA/Longest_Valid_Parentheses.cpp
Labels: Hacktoberfest Accepted

#153 Added Trapping_rain_water_problem.java
  Trapping_rain_water_problem.java
Labels: Hacktoberfest Accepted

#154 Create pstree.sh
  pstree.sh
Labels: Hacktoberfest Accepted

#156 Create BulkFileRenameTool.py
  BulkFileRenameTool.py
Labels: Hacktoberfest Accepted

#158 Add files via upload
  calculator.cpp
Labels: Hacktoberfest Accepted

#162 two numbers are friendly pair or not
  DSA/friendlypair.c
Labels: Hacktoberfest Accepted

#163 Automorphic Number or Not
  DSA/Automorphic.c
Labels: Hacktoberfest Accepted

#164 Octal To Binary Conversion
  DSA/octalbinary.c
Labels: Hacktoberfest Accepted

#165 Find all symmetric elements in an array
  DSA/symmetric.c
Labels: Hacktoberfest Accepted, Under review

#169 Create Complement10.cpp
  DSA/Complement10.cpp
Labels: Hacktoberfest Accepted

#171 Create String_to_Int.cpp
  DSA/String_to_Int.cpp
Labels: Hacktoberfest Accepted

#166 bash script to control the life cycle of xclock
  DSA/bash-programmig/xprocess.sh
Labels: Hacktoberfest Accepted

#170 added pattern.cpp
  pattern.cpp
Labels: Hacktoberfest Accepted

#167 Create Jump_game_2.cpp
  Jump_game_2.cpp
Labels: Hacktoberfest Accepted

#168 Add files via upload
  Fake_News_Detection.ipynb
Labels: Hacktoberfest Accepted

#175 Linked List Programs Added
  DSA/Doubly_Linked_List.cpp
  DSA/Singly_Linked_List.cpp
Labels: Hacktoberfest Accepted

#176 Solution of CP problem Different Divisors
  CP/DifferentDivisors.java
  CP/DoubleEndedString.java
Labels: Hacktoberfest Accepted

#178 Solution for CP program Strange Table
  CP/StrangeTable.java
Labels: Hacktoberfest Accepted

#179 Solution for Strange Functions
  CP/StrangeFunctions.java
Labels: Hacktoberfest Accepted

#180 Solution for Almost Rectangle
  CP/AlmostRectangle.java
Labels: Hacktoberfest Accepted

#182 Solution for Puzzle From Future
  CP/PuzzleFromFuturea.java
Labels: Hacktoberfest Accepted

#183 Solution for CP program String LCM
  CP/StringLCM.cpp
Labels: Hacktoberfest Accepted

#185 Solution for CP program MatrixChainMultiplication
  CP/MatrixChainMultiplication (1).cpp
Labels: Hacktoberfest Accepted

#186 Solution for CP problem YetAnotherPalindrome
  CP/YetAnotherPalindromeProblem.java
Labels: Hacktoberfest Accepted

#187 Solution for All Strings Containing K Characters
  CP/AllStringsContaingKChars.java
Labels: Hacktoberfest Accepted

#188 Solution for Balanced Remainders
  CP/BalancedRemainders.java
Labels: Hacktoberfest Accepted

#189 Solution for Validate IP address
  CP/ValidateAnIPAddress.java
Labels: Hacktoberfest Accepted

#191 buildingRace.java
  buildingRace.java
Labels: Hacktoberfest Accepted
